In [42]:
import pandas as pd

# Wczytanie pliku i wyÅ›wietlenie oryginalnej tablicy
direction = "C:/Users/WINKLER/Desktop/AiBD/analiza-i-bazy-danych/Analiza_i_bazy_danych/Lab_2/OriginalData/billboard.csv"

billboards = pd.read_csv(direction)
billboards

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
#  Wczytanie danych i usuniÄ™cie pustych kolumn

billboards = pd.read_csv(direction)
billboards = billboards.dropna(axis = 1, how = 'any')
billboards

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57
...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99

In [44]:
# Wczytanie pliku oryginalnego

billboards = pd.read_csv(direction)

# UsuniÄ™cie pustych kolumn
billboards = billboards.dropna(axis = 1, how = 'any')

# UporzÄ…dkowane dane - moÅ¼liwoÅ›Ä‡ odczytania jakÄ… pozycjÄ™ na liÅ›cie 
# zajmowali konkretni artyÅ›ci (2 kolumna) ze swoimi utworami (3 kolumna) w pierwszym tygodniu 
# zestawienia (4 kolumna)
billboard_new = billboards[['artist.inverted', 'track', 'x1st.week']].sort_values('x1st.week')
billboard_new

                  artist.inverted                       track  x1st.week
1                         Santana                Maria, Maria         15
80                         Hanson            This Time Around         22
45                           Pink                  There U Go         25
114                 Carey, Mariah                     Crybaby         28
35   Elliott, Missy "Misdemeanor"                    Hot Boyz         36
..                            ...                         ...        ...
303                       Lil' Mo                       Ta Da        100
300                   Herndon, Ty                    No Mercy        100
307                Larrieux, Amel                      Get Up        100
248                         Drama           Left, Right, Left        100
47                          Nelly  (Hot S**t) Country Grammar        100

[317 rows x 3 columns]

In [45]:
# Stworzenie nowego pliku z czytelnym rankingiem w pierwszym tygodniu

billboard_new.to_csv(path_or_buf="C:/Users/WINKLER/Desktop/AiBD/analiza-i-bazy-danych/Analiza_i_bazy_danych/Lab_2/AnalysisData/billboard_new.csv", index=False)
print(billboard_new)

                  artist.inverted                       track  x1st.week
1                         Santana                Maria, Maria         15
80                         Hanson            This Time Around         22
45                           Pink                  There U Go         25
114                 Carey, Mariah                     Crybaby         28
35   Elliott, Missy "Misdemeanor"                    Hot Boyz         36
..                            ...                         ...        ...
303                       Lil' Mo                       Ta Da        100
300                   Herndon, Ty                    No Mercy        100
307                Larrieux, Amel                      Get Up        100
248                         Drama           Left, Right, Left        100
47                          Nelly  (Hot S**t) Country Grammar        100

[317 rows x 3 columns]